# Typ Variable (proměnná)

Typ variable je specifický kontejner pro uchování Tensorů, které mohou být v průběhu procesu učení měněny optimalizačními funkcemi Tensorflow. Tensor variable může být:

- jediná hodnota - skalár
- jednorozměrné pole hodnot - vektor
- vícerozměrné pole hodnot - matice

In [1]:
import tensorflow as tf

Tensor variable může být definován například takto:

In [2]:
a = tf.Variable(42.0, name="skalar_a")
b = tf.Variable((1, 2, 3, 4), name="vektor_b")
c = tf.Variable(tf.random_uniform([3, 3], -1, 1), name="matice_c") 

'jméno proměnné' tensor jednoznačně identifikuje. Pomocí jména proměnné je také možné se na proměnnou odkazovat. Pokud jméno proměnné není definováno, Tensorflow přiřadí proměnné unikátní jméno.

In [3]:
#trainable_vars = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES) # only trainable vars
tf_vars = tf.global_variables()

for tf_var in tf_vars:
    print(tf_var.name)

skalar_a:0
vektor_b:0
matice_c:0


Funkce get_shape slouží pro získání informace o 'rozměru' tensoru. Na příkladě uvedeném níže je proměnná (a) skalár; (b) vektor; (c) matice. 

In [4]:
print('(a) shape: ', a.get_shape())
print('(b) shape: ', b.get_shape())
print('(c) shape: ', c.get_shape())

(a) shape:  ()
(b) shape:  (4,)
(c) shape:  (3, 3)


Vytvářet tensory typu variable je možné též pomocí funkce tf.get_variable. Povinným parametrem této funkce je 'jméno proměnné'. 

In [5]:
x = tf.get_variable("var_x", shape=(), initializer=tf.zeros_initializer())
y = tf.get_variable("var_y", [4], initializer=tf.constant_initializer(0.0))
z = tf.get_variable("var_z", [3, 3], initializer=tf.random_normal_initializer())

In [6]:
print('x shape: ', x.get_shape())
print('y shape: ', y.get_shape())
print('z shape: ', z.get_shape())

x shape:  ()
y shape:  (4,)
z shape:  (3, 3)


Pokud nechceme, aby byl při procesu učení tensor typu variable modifikován, pak v definici variable použijeme parametr <i>trainable=False</i>.

In [7]:
d = tf.Variable(42.0, trainable=False)

In [24]:
sess.close()

# Typ Variable - inicializace, metoda global_variables_initializer()

Vytvoříme novou Session: 

In [25]:
sess = tf.Session()

U tensoru typu variable vždy potřebujeme provést počáteční inicializaci. V rámci inicializace budou našim tensorům typu variable přiřazeny počáteční hodnoty. 

In [27]:
sess.run(tf.global_variables_initializer())

In [28]:
print('(a): \n', a.eval(session=sess))
print('(b): \n', b.eval(session=sess))
print('(c): \n', c.eval(session=sess))

(a): 
 42.0
(b): 
 [1 2 3 4]
(c): 
 [[ 0.51312351 -0.57280779  0.6515882 ]
 [-0.31022811  0.30629182 -0.76460338]
 [-0.4701488   0.22626591  0.42931581]]


In [29]:
print('(x): \n', x.eval(session=sess))
print('(y): \n', y.eval(session=sess))
print('(z): \n', z.eval(session=sess))

(x): 
 0.0
(y): 
 [ 0.  0.  0.  0.]
(z): 
 [[ 0.26258507 -0.64393932  1.25223124]
 [ 1.08484638  1.21216989  0.21465681]
 [ 1.64528096  1.56341434 -0.08879239]]


In [30]:
sess.close()

# Typ Variable - inicializace, metoda initializer.run()

Metoda initializer.run() další způsob, jak provést inicializaci tensoru variable.

In [36]:
sess = tf.Session()

In [37]:
a.initializer.run(session=sess)
b.initializer.run(session=sess)
c.initializer.run(session=sess)

In [38]:
print('(a): \n', a.eval(session=sess))
print('(b): \n', b.eval(session=sess))
print('(c): \n', c.eval(session=sess))

(a): 
 42.0
(b): 
 [1 2 3 4]
(c): 
 [[-0.77819848 -0.464926    0.71787381]
 [ 0.63302493 -0.61534238 -0.83571386]
 [ 0.11454892 -0.64117146 -0.27751398]]


In [41]:
x.initializer.run(session=sess)
y.initializer.run(session=sess)
z.initializer.run(session=sess)

In [46]:
print('(x): \n', x.eval(session=sess))
print('(y): \n', y.eval(session=sess))
print('(z): \n', z.eval(session=sess))

(x): 
 0.0
(y): 
 [ 0.  0.  0.  0.]
(z): 
 [[ 0.25277686 -0.32317629  0.43126944]
 [-1.1132611  -0.35356668  0.74354833]
 [ 0.10898042  1.02042317  2.44411302]]


In [47]:
sess.close()

# Typ Variable - další operace

Přiřazení hodnoty (setter) proměnné (x).

In [55]:
assignment = x.assign(42)

Operace inkrement a dekrement nad tensorem typu variable:

In [56]:
increment_x = x.assign_add(1)
decrement_x = x.assign_sub(1)

Operace přiřazení, inkrement a dekrement musíme volat z platné session, např.:

In [57]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())
print('(x) init: \n', x.eval(session=sess))

sess.run(assignment)
print('(x) assignment: \n', x.eval(session=sess))

sess.run(increment_x)
print('(x) increment: \n', x.eval(session=sess))

sess.run(decrement_x)
print('(x) increment: \n', x.eval(session=sess))

sess.close()

(x) init: 
 0.0
(x) assignment: 
 42.0
(x) increment: 
 43.0
(x) increment: 
 42.0


Výpis všech proměnnýhc typu trainable: 

In [58]:
for tf_trainable in tf.trainable_variables():
    print(tf_trainable.name)

skalar_a:0
vektor_b:0
matice_c:0
var_x:0
var_y:0
var_z:0


Uložení hodnot tensoru typu variable: (TBD)

Na Tensor typu Variable nemůže být použita operace reshape, např. n.reshape(n, [2, 6]).

# Odkazy:

https://www.tensorflow.org/programmers_guide/variables