# Typ Variable

In [1]:
import tensorflow as tf

Typ variable (proměnná) se používá pro uložení parametrů, které jsou při procesu učení  modifikovány. Pokud nechceme optimalizačním funkcím Tensorflow dovolit, aby při procesu učení proměnnou mělily, pak jako parametr při definici proměnné použijeme trainable=False (default je True). Novou proměnnou definujeme například takto:

In [6]:
a = tf.Variable(42.0, trainable=False)
b = tf.Variable((1, 2, 3, 4))
c = tf.Variable(tf.random_uniform([3, 3], -1, 1), name="c") 

Funkce get_shape slouží pro získání informace o 'rozměru' tensoru. Na příkladě uvedeném níže je proměnná (a) zero-order tensor : skalár; (b) first-orter tensor : vektor; (c) second-order tensor: matice. 

In [7]:
print('(a) shape: ', a.get_shape())
print('(b) shape: ', b.get_shape())
print('(c) shape: ', c.get_shape())

(a) shape:  ()
(b) shape:  (4,)
(c) shape:  (3, 3)


Vytvářet tensory typu variable je možné i pomocí funkce tf.get_variable. Tato funkce vyžaduje parametr 'Variable name' : 'jméno proměnné'. 'Variable name' jednoznačně identifikuje proměnnou v Grafu.

In [8]:
x = tf.get_variable("x", shape=(), initializer=tf.zeros_initializer())
y = tf.get_variable("y", [4], initializer=tf.constant_initializer(0.0))
z = tf.get_variable("z", [3, 3], initializer=tf.random_normal_initializer())

In [9]:
print('x shape: ', x.get_shape())
print('y shape: ', y.get_shape())
print('z shape: ', z.get_shape())

x shape:  ()
y shape:  (4,)
z shape:  (3, 3)


# Typ Variable - inicializace, metoda global_variables_initializer()

Pro typ Variable, oproti ostatním typům, vždy potřebujeme provést počáteční inicializaci.

In [10]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [11]:
print('(a): ', a.eval(session=sess))
print('(b): ', b.eval(session=sess))
print('(c): ', c.eval(session=sess))

(a):  42.0
(b):  [1 2 3 4]
(c):  [[-0.84106374 -0.33695173  0.62760663]
 [-0.85483694  0.1840713   0.61371231]
 [ 0.55979395  0.44429755 -0.10017323]]


In [12]:
print('(x): ', x.eval(session=sess))
print('(y): ', y.eval(session=sess))
print('(z): ', z.eval(session=sess))

(x):  0.0
(y):  [ 0.  0.  0.  0.]
(z):  [[ 0.60535711 -2.2907331   1.29542804]
 [ 1.83471262  0.01551907  0.68117017]
 [ 0.49631745  1.70548594  0.21026595]]


In [13]:
sess.close()

# Typ Variable - inicializace, metoda initializer.run()

In [15]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

Provést inicializaci Tensouru Variable můžeme i pomocí metody initializer.

In [16]:
a.initializer.run(session=sess)
b.initializer.run(session=sess)
c.initializer.run(session=sess)

In [18]:
print('(a): ', a.eval(session=sess))
print('(b): ', b.eval(session=sess))
print('(c): ', c.eval(session=sess))

(a):  42.0
(b):  [1 2 3 4]
(c):  [[-0.20951295 -0.32593584  0.98399758]
 [ 0.15748119 -0.59481239  0.57189703]
 [ 0.05034971  0.62448668  0.3363421 ]]


In [17]:
x.initializer.run(session=sess)
y.initializer.run(session=sess)
z.initializer.run(session=sess)

In [19]:
print('(x): ', x.eval(session=sess))
print('(y): ', y.eval(session=sess))
print('(z): ', z.eval(session=sess))

(x):  0.0
(y):  [ 0.  0.  0.  0.]
(z):  [[-0.03822499  0.02282218  0.56976432]
 [ 0.26900336  1.1861012  -0.72477859]
 [-1.21657956 -0.23759468 -0.61177611]]


In [ ]:
sess.close()

# Typ Variable - další operace

Přiřazení hodnoty (setter) proměnné <b>x</b>.

In [22]:
assignment = x.assign(1)

Přiřazení musíme volat z platné session:

In [23]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print('x after init: ', x.eval(session=sess))
sess.run(assignment)
print('x after assignment: ', x.eval(session=sess))

x after init:  0.0
x after assignment:  1.0


Na Tensor typu Variable nemůže být použita operace reshape, např. n.reshape(n, [2, 6]).

In [24]:
sess.close()

# Odkazy:

https://www.tensorflow.org/programmers_guide/variables