# Typ Variable (proměnná)

Typ variable je specifický kontejner pro uchování Tensorů, které mohou být v průběhu procesu učení měněny optimalizačními funkcemi Tensorflow. Tensor variable může být:

- jediná hodnota - skalár
- jednorozměrné pole hodnot - vektor
- vícerozměrné pole hodnot - matice

In [1]:
import tensorflow as tf

Tensor variable může být definován například takto:

In [2]:
a = tf.Variable(42.0)
b = tf.Variable((1, 2, 3, 4), name="vektor_b")
c = tf.Variable(tf.random_uniform([3, 3], -1, 1), name="matice_c") 

'jméno proměnné' proměnnou jednoznačně identifikuje a přes jméno proměnné je také možné k proměnné přistupovat. Pokud není definováno parametrem 'name', pak Tensorflow přiřadí proměnné unikátní jméno sám.

In [3]:
#trainable_vars = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES) # only trainable vars
tf_vars = tf.global_variables()

for tf_var in tf_vars:
    print(tf_var.name)

Variable:0
vektor_b:0
matice_c:0


Funkce get_shape slouží pro získání informace o 'rozměru' tensoru. Na příkladě uvedeném níže je proměnná (a) skalár; (b) vektor; (c) matice. 

In [4]:
print('(a) shape: ', a.get_shape())
print('(b) shape: ', b.get_shape())
print('(c) shape: ', c.get_shape())

(a) shape:  ()
(b) shape:  (4,)
(c) shape:  (3, 3)


Vytvářet tensory typu variable je možné též pomocí funkce tf.get_variable. Povinným parametrem této funkce je 'jméno proměnné'. 

In [5]:
x = tf.get_variable("var_x", shape=(), initializer=tf.zeros_initializer())
y = tf.get_variable("var_y", [4], initializer=tf.constant_initializer(0.0))
z = tf.get_variable("var_z", [3, 3], initializer=tf.random_normal_initializer())

In [6]:
print('x shape: ', x.get_shape())
print('y shape: ', y.get_shape())
print('z shape: ', z.get_shape())

x shape:  ()
y shape:  (4,)
z shape:  (3, 3)


Pokud nechceme optimalizačním funkcím Tensorflow dovolit, aby při procesu učení proměnnou modifikovaly, pak jako parametr při definici proměnné použijeme trainable=False (default je True).

In [7]:
d = tf.Variable(42.0, trainable=False)

# Typ Variable - inicializace, metoda global_variables_initializer()

In [17]:
sess = tf.Session()

Tensor typu variable se ještě oproti ostatním typům Tensorů liší tím, že u něj vždy potřebujeme provést počáteční inicializaci.

In [18]:
sess.run(tf.global_variables_initializer())

Inicializace zajistí, že tensorům variable budou přiřazeny počáteční hodnoty. 

In [19]:
print('(a): ', a.eval(session=sess))
print('(b): ', b.eval(session=sess))
print('(c): ', c.eval(session=sess))

(a):  42.0
(b):  [1 2 3 4]
(c):  [[ 0.09743547 -0.88294291  0.05065894]
 [-0.69939089 -0.49960637 -0.8659234 ]
 [-0.38385177 -0.76335955  0.85702324]]


In [20]:
print('(x): ', x.eval(session=sess))
print('(y): ', y.eval(session=sess))
print('(z): ', z.eval(session=sess))

(x):  0.0
(y):  [ 0.  0.  0.  0.]
(z):  [[-0.42074251 -0.46938169 -0.91593695]
 [ 0.40945992  0.21662033  0.1658165 ]
 [-0.29393718 -1.68344557 -0.84493709]]


In [21]:
sess.close()

# Typ Variable - inicializace, metoda initializer.run()

In [23]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

Metoda initializer.run() další způsob, jak provést inicializaci tensoru variable.

In [24]:
a.initializer.run(session=sess)
b.initializer.run(session=sess)
c.initializer.run(session=sess)

In [25]:
print('(a): ', a.eval(session=sess))
print('(b): ', b.eval(session=sess))
print('(c): ', c.eval(session=sess))

(a):  42.0
(b):  [1 2 3 4]
(c):  [[-0.90079927  0.28887773 -0.28051114]
 [ 0.6285007  -0.87906694  0.49476457]
 [-0.34386992 -0.07344246 -0.79805827]]


In [26]:
x.initializer.run(session=sess)
y.initializer.run(session=sess)
z.initializer.run(session=sess)

In [27]:
print('(x): ', x.eval(session=sess))
print('(y): ', y.eval(session=sess))
print('(z): ', z.eval(session=sess))

(x):  0.0
(y):  [ 0.  0.  0.  0.]
(z):  [[-0.82243264  2.68513203 -0.72563618]
 [ 0.64587867  0.08906178  0.36961961]
 [ 0.54944187 -1.03327966 -0.87190086]]


In [28]:
sess.close()

# Typ Variable - další operace

Přiřazení hodnoty (setter) proměnné (x).

In [32]:
assignment = x.assign(1)

Přiřazení musíme volat z platné session:

In [33]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print('(x) after init: ', x.eval(session=sess))
sess.run(assignment)
print('(x) after assignment: ', x.eval(session=sess))

(x) after init:  0.0
(x) after assignment:  1.0


Na Tensor typu Variable nemůže být použita operace reshape, např. n.reshape(n, [2, 6]).

In [34]:
sess.close()

# Odkazy:

https://www.tensorflow.org/programmers_guide/variables