# Typ placeholder

Pomocí placeholderu vkládáme data do Grafu.

In [1]:
import tensorflow as tf

nr_inputs = 2
a = tf.placeholder(tf.float32, [nr_inputs, 4], name='muj_placeholder_a')
b = tf.placeholder(tf.float32, [nr_inputs, 4], name='muj_placeholder_b')

c = tf.add(a, b)

data_feed_a = [[1., 2., 3., 4.], [5., 6., 7., 8.]]
data_feed_b = [[9., 0., 1., 2.], [3., 4., 5., 6.]]

sess = tf.Session()

res_a, res_b, res_c = sess.run([a, b, c], feed_dict={a: data_feed_a, b: data_feed_b})
print('a: ')
print(res_a)
print('b: ')
print(res_b)
print('c = a + b: ')
print(res_c)

a: 
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]]
b: 
[[ 9.  0.  1.  2.]
 [ 3.  4.  5.  6.]]
c = a + b: 
[[ 10.   2.   4.   6.]
 [  8.  10.  12.  14.]]


In [2]:
sess.close()